server:
  port: 8080
  servlet:
    context-path: /c2c

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/alc-local?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
  redis:
    host: 192.168.99.11
    port: 6379

logging:
  level: debug
  level.com.exchange.c2c: debug
  path: logs/
  file: c2c.log

cors:
  origins: "*"